# Update the API documentation whenever the `main` branch changes.
# This documentation lives in its own `docs` branch.
name: docs

on:
  push:
    branches:
      - 'main'

jobs:
  update-docs-branch:
    runs-on: ubuntu-20.04 # latest
    permissions:
      contents: write # allow push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update docs branch
        run: |
          echo "Compiling doxygen 1.8.20 from source"
          sudo apt-get install -y llvm-10 clang-10 libclang-10-dev
          git clone https://github.com/doxygen/doxygen.git -b Release_1_8_20
          cd doxygen
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -Duse_libclang=ON ..
          make
          make install
          cd ../..

          version=$(git describe --tags --abbrev=0)
          sed -i -r -e "s/PROJECT_NUMBER         = .*$PARTITION_COLUMN.*/PROJECT_NUMBER         = ${version//v}/" docsrc/doxygen.config
          echo "Updating AWS_SDK_CPP_VERSION default to ${version//v}"

          ./make-docs.py

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --force docs/
          git commit --message="update docs"

      - name: Push to docs branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ github.token }}
          branch: docs
          # Force push so that `docs` branch always looks like `main`,
          # but with 1 additional "update docs" commit.
          # This seems simpler than trying to cleanly merge `main` into
          # `docs` each time.
          force: true
